vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        registro_historial:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        registro_recomendacion:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer